/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

export interface GuideCategory {
    id: string;
    label: string;
    description: string;
}

export const GUIDE_CATEGORIES: GuideCategory[] = [
    {
        id: "core",
        label: "Moggcord Basis",
        description: "Updates, Stabilität und zentrale Moggcord-Funktionen.",
    },
    {
        id: "chat",
        label: "Chat & Nachrichten",
        description: "Logging, Übersetzung, Antworten und Nachrichten-Tools.",
    },
    {
        id: "voice",
        label: "Voice & Audio",
        description: "Sprachkanäle, Audio-Qualität und Voice-Features.",
    },
    {
        id: "ui",
        label: "Design & UI",
        description: "Themes, Animationen und visuelle Anpassungen.",
    },
    {
        id: "privacy",
        label: "Privatsphäre",
        description: "Stealth, Stream-Schutz und unsichtbare Aktionen.",
    },
    {
        id: "tools",
        label: "Tools & Utilities",
        description: "Export, Suche, Multi-Account und praktische Helfer.",
    },
    {
        id: "advanced",
        label: "Erweitert",
        description: "Power-User-Features — mit Vorsicht verwenden.",
    },
    {
        id: "other",
        label: "Weitere Plugins",
        description: "Sonstige standardmäßig aktive Plugins.",
    },
];

/** Explicit category for Moggcord plugins (others fall back to keyword rules). */
export const PLUGIN_CATEGORY: Record<string, string> = {
    MoggcordHub: "core",
    MoggcordUpdater: "core",
    MoggcordAI: "core",
    uiRelaunchFix: "core",
    crashHandler: "core",
    autoTranslateMoggcord: "core",
    equicordHelper: "core",
    themeLibrary: "ui",
    createTheme: "ui",
    settingsGlint: "ui",
    SmoothType: "ui",
    channelWallpaper: "ui",
    liveWallpaper: "ui",
    userAreaTweaks: "ui",
    cleanHomeSidebar: "ui",
    titlebarLink: "ui",
    macOsButtons: "ui",
    realtimeTimestamps: "ui",
    memberCount: "ui",
    platformIndicators: "ui",
    iconViewer: "ui",
    viewIcons: "ui",
    imageZoom: "ui",
    doubleEmoji: "ui",
    pinDms: "ui",
    MessageLogger: "chat",
    MessageLoggerEnhanced: "chat",
    antiDeleteMessage: "chat",
    silentDelete: "chat",
    silentEdit: "chat",
    translate: "chat",
    autoReply: "chat",
    autoResponder: "chat",
    autoCorrect: "chat",
    exportDM: "chat",
    messageCleaner: "chat",
    encryptedMessage: "chat",
    selfDestruct: "chat",
    hideAttachments: "chat",
    abreviation: "chat",
    validUser: "chat",
    cancelFriendRequest: "chat",
    showHiddenChannels: "chat",
    showHiddenThings: "chat",
    eventLogs: "chat",
    VolumeBooster: "voice",
    voiceMessages: "voice",
    voiceDictation: "voice",
    voiceDownload: "voice",
    voiceRejoin: "voice",
    voiceChannelSearch: "voice",
    callTimer: "voice",
    userVoiceShow: "voice",
    whosWatching: "voice",
    disableCallIdle: "voice",
    fixKrisp: "voice",
    FakeVoice: "voice",
    doubleCall: "voice",
    audioLimiter: "voice",
    noNitroUpsell: "voice",
    stealthMode: "privacy",
    streamProof: "privacy",
    ghostClient: "privacy",
    alwaysTrust: "privacy",
    noUnblockToJump: "privacy",
    multiInstance: "tools",
    tokenImporter: "tools",
    unlimitedAccounts: "tools",
    betterSessions: "tools",
    reverseImageSearch: "tools",
    sharePerms: "tools",
    bulkFriendRemove: "tools",
    leaveAllServers: "tools",
    serverCloner: "tools",
    followUser: "tools",
    followMe: "tools",
    lockGroup: "tools",
    inRole: "tools",
    muteAllServers: "tools",
    bigFileUpload: "tools",
    backpack: "tools",
    customProfile: "tools",
    soundcloudPlayer: "tools",
    spotifyCrack: "tools",
    wordBomb: "tools",
    KeyboardSounds: "tools",
    overlayFix: "tools",
    fixScreenshare: "tools",
    antiMoveDeco: "tools",
    antiNickname: "tools",
    massDM: "advanced",
    DMBomb: "advanced",
    fakeAccount: "advanced",
    fakeDM: "advanced",
    fakeFriends: "advanced",
    impersonate: "advanced",
    floodPanel: "advanced",
    platformSpoofer: "advanced",
};

/** German descriptions where the default English text is too terse. */
export const DESCRIPTION_DE: Record<string, string> = {
    MoggcordHub: "Zentrale für News, Changelog und Plugin-Guide — ersetzt den Shop in der DM-Leiste.",
    MoggcordUpdater: "Sucht beim Start nach Updates auf GitHub und zeigt einen grünen Banner.",
    MoggcordAI: "KI-Chat (Groq) — optional, ersetzt den Shop-Tab wenn aktiviert.",
    uiRelaunchFix: "Behebt UI-Probleme nach einem Discord-Neustart.",
    crashHandler: "Fängt Client-Abstürze ab und hilft beim Recovery.",
    autoTranslateMoggcord: "Übersetzt Moggcord-UI-Texte in deine Sprache.",
    themeLibrary: "Theme-Bibliothek — installiere und verwalte Discord-Themes.",
    settingsGlint: "Dezenter Glanz-Effekt in den Moggcord-Einstellungen.",
    SmoothType: "Sanftere Tipp-Animation im Chat-Eingabefeld.",
    MessageLogger: "Speichert gelöschte und bearbeitete Nachrichten lokal.",
    MessageLoggerEnhanced: "Erweitert den Message Logger mit History, Ghost Pings und mehr.",
    antiDeleteMessage: "Markiert gelöschte Nachrichten und kann sie sichtbar halten.",
    translate: "Übersetzt Nachrichten per Klick oder Kontextmenü.",
    showHiddenChannels: "Zeigt versteckte Kanäle und Lock-Screens für Voice/Text.",
    stealthMode: "Versteckt Moggcord-UI-Elemente für Screenshots und Streams.",
    streamProof: "Versteckt Moggcord aus Discord-Screenshare und OBS.",
    multiInstance: "Zweites Discord-Fenster mit anderem Account.",
    VolumeBooster: "Erhöht die Lautstärke in Voice-Channels über 100 %.",
    voiceMessages: "Sende Sprachnachrichten wie bei Messengern.",
    voiceDictation: "Diktiere Text per Mikrofon in das Chat-Feld (Groq).",
    bigFileUpload: "Lädt größere Dateien hoch als Discord normal erlaubt.",
    exportDM: "Exportiert DM-Verläufe als HTML oder JSON.",
    serverCloner: "Kopiert Server-Struktur (Kanäle, Rollen) auf einen neuen Server.",
    pinDms: "Pinne wichtige DMs oben in der Liste.",
    realtimeTimestamps: "Live-aktualisierte Zeitstempel (z. B. „vor 3 Sek.“).",
    noNitroUpsell: "Entfernt Nitro-Werbung und Upsell-Popups.",
    alwaysTrust: "Überspringt Warnungen bei externen Links und Downloads.",
    autoReply: "Automatische Antworten auf eingehende Nachrichten.",
    autoResponder: "Regelbasierte Auto-Antworten mit Keywords.",
    memberCount: "Zeigt Mitglieder- und Online-Zähler im Server.",
    callTimer: "Timer für laufende Voice-/Video-Calls.",
    encryptedMessage: "Verschlüsselte Nachrichten mit Passwort.",
    selfDestruct: "Nachrichten die sich nach einer Zeit selbst löschen.",
    muteAllServers: "Stummschaltet alle Server und markiert als gelesen per Rechtsklick.",
    sharePerms: "Teile temporäre Berechtigungen mit anderen Usern.",
    customProfile: "Erweiterte Profil-Anpassungen über Discord hinaus.",
    soundcloudPlayer: "Spiele SoundCloud-Links direkt in Discord ab.",
    wordBomb: "Minispiel Word Bomb im Chat.",
    KeyboardSounds: "Tippgeräusche beim Schreiben im Chat.",
    cancelFriendRequest: "Freundschaftsanfragen abbrechen statt nur ablehnen.",
    cleanHomeSidebar: "Räumt die Home-Sidebar auf.",
    userAreaTweaks: "Kleine Anpassungen am User-Bereich unten links.",
    channelWallpaper: "Eigene Hintergrundbilder pro Kanal.",
    liveWallpaper: "Animierte Hintergründe für Discord.",
    imageZoom: "Bilder im Chat vergrößern und zoomen.",
    reverseImageSearch: "Bilder per Rechtsklick bei Google/Lens suchen.",
    eventLogs: "Protokolliert Server-Events (Joins, Bans, etc.).",
    tokenImporter: "Accounts per Token importieren und wechseln.",
    unlimitedAccounts: "Entfernt Discords Account-Limit.",
    betterSessions: "Bessere Session-Verwaltung für Multi-Account.",
    ghostClient: "Reduziert sichtbare Online-/Activity-Spuren.",
    noUnblockToJump: "Springe zu Nachrichten ohne User entblocken zu müssen.",
    fixKrisp: "Behebt Krisp/Noise-Suppression-Probleme.",
    voiceChannelSearch: "Suche in Voice-Channels und der Mitgliederliste.",
    voiceRejoin: "Tritt Voice automatisch wieder bei nach Disconnect.",
    userVoiceShow: "Zeigt wer in welchem Voice-Channel ist.",
    whosWatching: "Zeigt wer deinen Stream/Screenshare zuschaut.",
    disableCallIdle: "Verhindert dass Calls wegen Inaktivität beendet werden.",
    doubleCall: "Zwei parallele Calls in verschiedenen Channels.",
    massDM: "Massen-DMs an viele User — nur verantwortungsvoll nutzen.",
    DMBomb: "Sendet viele DMs schnell hintereinander — Advanced-Tool.",
    fakeAccount: "Simuliert Fake-Accounts in der UI — nur zu Testzwecken.",
    impersonate: "Sende Nachrichten mit fremdem Namen/Avatar (lokal sichtbar).",
    floodPanel: "Panel zum schnellen Senden vieler Nachrichten.",
    platformSpoofer: "Täuscht vor von welcher Plattform du Discord nutzt.",
    spotifyCrack: "Spotify-Integration ohne Premium-Beschränkungen.",
    backpack: "Speichere Nachrichten, Links und Medien in einer persönlichen Sammlung.",
    lockGroup: "Sperre Gruppen-DMs für neue Mitglieder.",
    inRole: "Zeigt wer eine bestimmte Rolle hat.",
    leaveAllServers: "Verlasse alle Server auf einmal.",
    bulkFriendRemove: "Entferne viele Freunde gleichzeitig.",
    followUser: "Folge einem User zwischen Voice-Channels.",
    followMe: "Andere können dir in Voice-Channels folgen.",
    abreviation: "Text-Abkürzungen die automatisch expandieren.",
    validUser: "Prüft ob eine User-ID gültig/existiert.",
    hideAttachments: "Blendet Anhänge standardmäßig aus bis du sie öffnest.",
    messageCleaner: "Löscht deine eigenen Nachrichten in Bulk.",
    silentDelete: "Löscht Nachrichten ohne sie lokal im Logger zu behalten.",
    silentEdit: "Bearbeitet Nachrichten ohne Edit-Hinweis.",
    autoCorrect: "Rechtschreibkorrektur beim Tippen (Groq).",
    autoUnmute: "Automatisches Entmuten in Voice.",
    antiMoveDeco: "Schützt vor ungewolltem Verschieben in Voice.",
    antiNickname: "Blockiert Nickname-Änderungen auf Servern.",
    doubleEmoji: "Sende doppelte Emoji-Größe in Nachrichten.",
    viewIcons: "Zeige Server-/Channel-Icons in voller Auflösung.",
    iconViewer: "Durchsuche und kopiere Discord-Icons.",
    titlebarLink: "Link in der Titelleiste zu Moggcord.",
    showHiddenThings: "Zeigt versteckte Discord-UI-Elemente.",
    fakeDM: "Erstellt Fake-DM-Konversationen in der UI.",
    fakeFriends: "Fake-Freunde in der Freundesliste — kosmetisch.",
    overlayFix: "Behebt Probleme mit dem Discord-Overlay.",
    fixScreenshare: "Verbessert Screenshare-Qualität und -Stabilität.",
};

const KEYWORD_CATEGORY: Array<{ id: string; pattern: RegExp; }> = [
    { id: "voice", pattern: /voice|audio|call|mute|krisp|sound|mic|dictation|volume/i },
    { id: "chat", pattern: /message|dm|chat|translate|reply|logger|edit|delete|timestamp|emoji/i },
    { id: "ui", pattern: /theme|wallpaper|smooth|ui|glint|sidebar|icon|zoom|button|type|profile|decor/i },
    { id: "privacy", pattern: /stealth|stream|ghost|hide|trust|proof|silent/i },
    { id: "advanced", pattern: /fake|bomb|flood|mass|imperson|spoof|crack/i },
    { id: "tools", pattern: /export|clone|import|instance|search|perm|server|follow|pin|upload|backpack/i },
];

export function resolveCategory(pluginName: string, description: string): string {
    if (PLUGIN_CATEGORY[pluginName]) return PLUGIN_CATEGORY[pluginName];

    const haystack = `${pluginName} ${description}`;
    for (const { id, pattern } of KEYWORD_CATEGORY) {
        if (pattern.test(haystack)) return id;
    }

    return "other";
}

export function getGermanDescription(pluginName: string, fallback: string): string {
    return DESCRIPTION_DE[pluginName] ?? fallback;
}
